# Generated by Django 4.2.6 on 2023-12-09 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
        ('codeSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('article_toggle_space', models.BooleanField(default=False)),
                ('code', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeSystem.uuidcode')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=20)),
                ('code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeSystem.uuidcode')),
                ('pType', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='article.articletype')),
                ('space', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemArticle', to='space.space')),
                ('stored', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space', to='space.space')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
    ]
