# Generated by Django 6.0.3 on 2026-03-29 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codeSystem', '0001_initial'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=20)),
                ('code', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeSystem.muidcode')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('amount', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeSystem.muidcode')),
                ('space', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemArticle', to='space.space')),
                ('stored', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space', to='space.space')),
                ('base', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='article.articlebase')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('article_toggle_space', models.BooleanField(default=False)),
                ('code', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeSystem.muidcode')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlebase',
            name='pType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='article.articletype'),
        ),
    ]
