# Generated by Django 6.0.3 on 2026-03-29 18:51

import django.db.models.deletion
import hub.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codeSystem', '0001_initial'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=20)),
                ('code', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeSystem.muidcode')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeSystem.muidcode')),
                ('parent', hub.fields.SelfForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.storage')),
                ('space', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemStorage', to='space.space')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storagetype')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
    ]
