# Generated by Django 6.0.3 on 2026-03-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuidCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('muidCodePretty', models.CharField(editable=False, max_length=13, unique=True)),
                ('muidCodeHash', models.BinaryField(unique=True)),
                ('codeReadable', models.CharField(editable=False, max_length=16, unique=True)),
                ('code', models.CharField(blank=True, editable=False, max_length=14, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=2)),
                ('used', models.BooleanField(default=True)),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
    ]
